### ISSUE TITLE
Schema for Graph

### ISSUE THREAD

**Issue by saulshanabrook** [plumatic/plumbing#119]
I have a few functions that take in graph definitions and it would be helpful for them to check that their inputs are proper graphs, when schema validation is enabled.

`(s/pred g/->graph)` does work as a schema, but the error trace isn't very helpful (`Output of wrap does not match schema: (throws? (plumbing.graph/->graph a-clojure.lang.PersistentArrayMap))`) because `g/->graph` raises an error instead of returning a boolean. Is there already a schema defined somewhere for a proper graph? I looked in https://github.com/plumatic/plumbing/blob/master/src/plumbing/fnk/schema.cljx but none seem to fit this use case.

**Comment by w01fe** [comment]
There isn't one that I know of.

The full semantics verified by ->graph can't be expressed as a schema
(besides how you say), but we could get better error messages in some cases
by capturing the structure more directly.  Something like:

(defn fnk? [x] (try (plumbing.fnk.pfnk/io-schemata x) true (catch Exception
e false)))

(s/defschema Fnk (s/pred fnk?))

(s/defschema GraphLike (s/cond-pre {s/Keyword (s/recursive #'Graph)} Fnk))

(s/defschema Graph (s/constrained GraphLike plumbing.graph/->graph))

(untested).  If this seems reasonable or you come up with something better,
happy to add it to the graph namespace.

**Comment by saulshanabrook** [comment]
@w01fe Your untested suggestion seems to work pretty well, although I haven't done any stress testing on it. I am using it, plus I also have made some constrained graphs that require at least a key:

```clojure
(def SearchGraph (s/constrained Graph #(contains? % :generations)))
```

It seem's like ideally the spec could support something like "This graphs requires these keys with these types and produces at least these keys with these types", but that might be overkill.

**Comment by w01fe** [comment]
Cool!  We'd be happy to include a generic Graph schema in the core plumbing lib, but I think anything fancier about specific types of graphs for a specific use case would be best kept outside the core lib at least for now.  Thanks!
