### ISSUE TITLE
lazymap's repository has been deleted, please migrate away from it

### ISSUE THREAD

**Issue by baldurmen** [plumatic/plumbing#137]
Hi!

This project depends on `de.kotka/lazymap`, but it seems its ~~git~~ mercurial repository has been deleted: https://bitbucket.org/kotarak/lazymap/. The project on clojars hasn't been updated since 2013 either, so I think it's fair to say that it's completely dead.

Would it be possible to move away from it? Not being able to build a dependency from source anymore makes me somewhat queasy...

If not, I guess another solution would be to rescue it from the [Software Heritage archive](https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://bitbucket.org/kotarak/lazymap), move it to git and host it in the `plumatic` namespace?

**Comment by w01fe** [comment]
Hi.  Thanks for pointing this out!  Unfortunately, I'm not really actively developing this library anymore, but I'm open to accepting pull requests if you want to help do something about this. 

It looks like the library is MIT licensed and I don't know if it can be directly included here, but I guess it would be possible to host and publish a fork.  We also used to have a lazy map implementation in-tree; I don't remember if it would fit all the current use cases but one could look into reverting the commit where we replaced that with the external dependency as another option.

**Comment by baldurmen** [comment]
> Hi. Thanks for pointing this out! Unfortunately, I'm not really actively developing this library anymore, but I'm open to accepting pull requests if you want to help do something about this.

Yeah, I totally get that, no problem. Sadly, I'm currently in no position to try to fix this either :(

Thanks for your work on plumbing!

**Comment by rlander** [comment]
Hey, I'm still a heavy plumbing user so I'd be interested in fixing this. @w01fe is this the in-tree implementation that you've mentioned? https://github.com/plumatic/plumbing/blob/356b4f09c54bf9a7a33bff8b598902238335cce2/src/plumbing/lazymap.clj

If so, it's the same lib minus a few bug fixes (and still MIT). I'll try to contact the author and see whether he'd be willing to release an eclipse licensed version that could be in-tree. Worth a try @w01fe ?

**Comment by w01fe** [comment]
Yeah, that's the one.  Hah, I had forgotten it was the same lib.  I'm sure I did my research at the time so it's probably OK to just go back to including the latest version in-tree with the license at the top as it was before.  Can't hurt to contact the author to double check though.  

Thanks, Jason

**Comment by desa** [comment]
@rlander any chance you were able to contact the previous library  maintainer?

**Comment by w01fe** [comment]
I went ahead and merged the fix, I'm sure I did the diligence at the time I originally brought it in tree.  Thanks!
