### ISSUE TITLE
Please consider making a new release

### ISSUE THREAD

**Issue by baldurmen** [plumatic/plumbing#144]
Hi!

Since plumbing doesn't use `cljx` anymore, it would be very nice if you could make a new release, if only for that. It would let me deprecate `cljx` in Debian for good :)

Cheers,

**Comment by w01fe** [comment]
I think `0.6.0` should be cljx-free?

**Comment by baldurmen** [comment]
Ah, that was released on Clojars, but there is no git tag in github :)

**Comment by w01fe** [comment]
Ah good point, thanks for pointing this out.  @frenchy64 released for the first time (thanks!) and probably followed a different process (the one I've used previously isn't documented, but is basically "run `bin/release.sh`" and is definitely a bit janky).  I'll add the tag when I get a chance.

**Comment by frenchy64** [comment]
I think I used `bin/release.sh` and it failed at the API documentation step (https://github.com/plumatic/plumbing/issues/143). Then I forgot to push the tag.

**Comment by frenchy64** [comment]
Actually I think there was an automated attempt to push, but I didn't have an upstream set or a remote named `origin`, so it failed.

**Comment by jcharaoui** [comment]
The lack of a tag for `0.6.0` is complicating things for the Debian packaging of this library.

Would it be possible to push a quick tag on 6773e8a5a9045330340073bfde2fce845b540103 ? Thanks.

**Comment by jcharaoui** [comment]
Thank you!!
